// Copyright zeroRISC Inc.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// AUTOGENERATED. Do not edit this file by hand.

#ifndef OPENTITAN_SW_DEVICE_LIB_CRYPTO_IMPL_ECC_P256_INSN_COUNTS_H_
#define OPENTITAN_SW_DEVICE_LIB_CRYPTO_IMPL_ECC_P256_INSN_COUNTS_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

enum {
% for mode, min_count, max_count in counts:
    // ${mode["comment"]}
    ${"k" + mode["const_str"] + "MinInstructionCount"} = ${0 if min_count is None else min_count},
    ${"k" + mode["const_str"] + "MaxInstructionCount"} = ${"UINT32_MAX" if max_count is None else max_count},
% endfor
};

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  // OPENTITAN_SW_DEVICE_LIB_CRYPTO_IMPL_ECC_P256_INSN_COUNTS_H_

