[mypy]
mypy_path = $MYPY_CONFIG_FILE_DIR/../../../../util
[mypy-semantic_version]
ignore_missing_imports = True
[mypy-hjson]
ignore_missing_imports = True
[mypy-jsonschema2md]
ignore_missing_imports = True
