// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// ------------------- W A R N I N G: A U T O - G E N E R A T E D   C O D E !! -------------------//
// PLEASE DO NOT HAND-EDIT THIS FILE. IT HAS BEEN AUTO-GENERATED WITH THE FOLLOWING COMMAND:
// util/gen_top_sw.py -t hw/top_dragonfly/data/autogen/top_dragonfly.gen.hjson

#include "hw/top_dragonfly/sw/autogen/top_dragonfly.h"

/**
 * Alert Handler Alert Source to Peripheral Map
 *
 * This array is a mapping from `top_dragonfly_alert_id_t` to
 * `top_dragonfly_alert_peripheral_t`.
 */
const top_dragonfly_alert_peripheral_t
    top_dragonfly_alert_for_peripheral[77] = {
  [kTopDragonflyAlertIdUart0FatalFault] = kTopDragonflyAlertPeripheralUart0,
  [kTopDragonflyAlertIdGpioFatalFault] = kTopDragonflyAlertPeripheralGpio,
  [kTopDragonflyAlertIdSpiDeviceFatalFault] = kTopDragonflyAlertPeripheralSpiDevice,
  [kTopDragonflyAlertIdI2c0FatalFault] = kTopDragonflyAlertPeripheralI2c0,
  [kTopDragonflyAlertIdRvTimerFatalFault] = kTopDragonflyAlertPeripheralRvTimer,
  [kTopDragonflyAlertIdOtpCtrlFatalMacroError] = kTopDragonflyAlertPeripheralOtpCtrl,
  [kTopDragonflyAlertIdOtpCtrlFatalCheckError] = kTopDragonflyAlertPeripheralOtpCtrl,
  [kTopDragonflyAlertIdOtpCtrlFatalBusIntegError] = kTopDragonflyAlertPeripheralOtpCtrl,
  [kTopDragonflyAlertIdOtpCtrlFatalPrimOtpAlert] = kTopDragonflyAlertPeripheralOtpCtrl,
  [kTopDragonflyAlertIdOtpCtrlRecovPrimOtpAlert] = kTopDragonflyAlertPeripheralOtpCtrl,
  [kTopDragonflyAlertIdLcCtrlFatalProgError] = kTopDragonflyAlertPeripheralLcCtrl,
  [kTopDragonflyAlertIdLcCtrlFatalStateError] = kTopDragonflyAlertPeripheralLcCtrl,
  [kTopDragonflyAlertIdLcCtrlFatalBusIntegError] = kTopDragonflyAlertPeripheralLcCtrl,
  [kTopDragonflyAlertIdSpiHost0FatalFault] = kTopDragonflyAlertPeripheralSpiHost0,
  [kTopDragonflyAlertIdPwrmgrAonFatalFault] = kTopDragonflyAlertPeripheralPwrmgrAon,
  [kTopDragonflyAlertIdRstmgrAonFatalFault] = kTopDragonflyAlertPeripheralRstmgrAon,
  [kTopDragonflyAlertIdRstmgrAonFatalCnstyFault] = kTopDragonflyAlertPeripheralRstmgrAon,
  [kTopDragonflyAlertIdClkmgrAonRecovFault] = kTopDragonflyAlertPeripheralClkmgrAon,
  [kTopDragonflyAlertIdClkmgrAonFatalFault] = kTopDragonflyAlertPeripheralClkmgrAon,
  [kTopDragonflyAlertIdPinmuxAonFatalFault] = kTopDragonflyAlertPeripheralPinmuxAon,
  [kTopDragonflyAlertIdAonTimerAonFatalFault] = kTopDragonflyAlertPeripheralAonTimerAon,
  [kTopDragonflyAlertIdSocProxyFatalAlertIntg] = kTopDragonflyAlertPeripheralSocProxy,
  [kTopDragonflyAlertIdSramCtrlRetAonFatalError] = kTopDragonflyAlertPeripheralSramCtrlRetAon,
  [kTopDragonflyAlertIdRvDmFatalFault] = kTopDragonflyAlertPeripheralRvDm,
  [kTopDragonflyAlertIdRvPlicFatalFault] = kTopDragonflyAlertPeripheralRvPlic,
  [kTopDragonflyAlertIdAccFatal] = kTopDragonflyAlertPeripheralAcc,
  [kTopDragonflyAlertIdAccRecov] = kTopDragonflyAlertPeripheralAcc,
  [kTopDragonflyAlertIdAesRecovCtrlUpdateErr] = kTopDragonflyAlertPeripheralAes,
  [kTopDragonflyAlertIdAesFatalFault] = kTopDragonflyAlertPeripheralAes,
  [kTopDragonflyAlertIdHmacFatalFault] = kTopDragonflyAlertPeripheralHmac,
  [kTopDragonflyAlertIdKmacRecovOperationErr] = kTopDragonflyAlertPeripheralKmac,
  [kTopDragonflyAlertIdKmacFatalFaultErr] = kTopDragonflyAlertPeripheralKmac,
  [kTopDragonflyAlertIdKeymgrDpeRecovOperationErr] = kTopDragonflyAlertPeripheralKeymgrDpe,
  [kTopDragonflyAlertIdKeymgrDpeFatalFaultErr] = kTopDragonflyAlertPeripheralKeymgrDpe,
  [kTopDragonflyAlertIdCsrngRecovAlert] = kTopDragonflyAlertPeripheralCsrng,
  [kTopDragonflyAlertIdCsrngFatalAlert] = kTopDragonflyAlertPeripheralCsrng,
  [kTopDragonflyAlertIdEntropySrcRecovAlert] = kTopDragonflyAlertPeripheralEntropySrc,
  [kTopDragonflyAlertIdEntropySrcFatalAlert] = kTopDragonflyAlertPeripheralEntropySrc,
  [kTopDragonflyAlertIdEdn0RecovAlert] = kTopDragonflyAlertPeripheralEdn0,
  [kTopDragonflyAlertIdEdn0FatalAlert] = kTopDragonflyAlertPeripheralEdn0,
  [kTopDragonflyAlertIdEdn1RecovAlert] = kTopDragonflyAlertPeripheralEdn1,
  [kTopDragonflyAlertIdEdn1FatalAlert] = kTopDragonflyAlertPeripheralEdn1,
  [kTopDragonflyAlertIdSramCtrlMainFatalError] = kTopDragonflyAlertPeripheralSramCtrlMain,
  [kTopDragonflyAlertIdSramCtrlMboxFatalError] = kTopDragonflyAlertPeripheralSramCtrlMbox,
  [kTopDragonflyAlertIdRomCtrl0Fatal] = kTopDragonflyAlertPeripheralRomCtrl0,
  [kTopDragonflyAlertIdRomCtrl1Fatal] = kTopDragonflyAlertPeripheralRomCtrl1,
  [kTopDragonflyAlertIdDmaFatalFault] = kTopDragonflyAlertPeripheralDma,
  [kTopDragonflyAlertIdMbx0FatalFault] = kTopDragonflyAlertPeripheralMbx0,
  [kTopDragonflyAlertIdMbx0RecovFault] = kTopDragonflyAlertPeripheralMbx0,
  [kTopDragonflyAlertIdMbx1FatalFault] = kTopDragonflyAlertPeripheralMbx1,
  [kTopDragonflyAlertIdMbx1RecovFault] = kTopDragonflyAlertPeripheralMbx1,
  [kTopDragonflyAlertIdMbx2FatalFault] = kTopDragonflyAlertPeripheralMbx2,
  [kTopDragonflyAlertIdMbx2RecovFault] = kTopDragonflyAlertPeripheralMbx2,
  [kTopDragonflyAlertIdMbx3FatalFault] = kTopDragonflyAlertPeripheralMbx3,
  [kTopDragonflyAlertIdMbx3RecovFault] = kTopDragonflyAlertPeripheralMbx3,
  [kTopDragonflyAlertIdMbx4FatalFault] = kTopDragonflyAlertPeripheralMbx4,
  [kTopDragonflyAlertIdMbx4RecovFault] = kTopDragonflyAlertPeripheralMbx4,
  [kTopDragonflyAlertIdMbx5FatalFault] = kTopDragonflyAlertPeripheralMbx5,
  [kTopDragonflyAlertIdMbx5RecovFault] = kTopDragonflyAlertPeripheralMbx5,
  [kTopDragonflyAlertIdMbx6FatalFault] = kTopDragonflyAlertPeripheralMbx6,
  [kTopDragonflyAlertIdMbx6RecovFault] = kTopDragonflyAlertPeripheralMbx6,
  [kTopDragonflyAlertIdMbxJtagFatalFault] = kTopDragonflyAlertPeripheralMbxJtag,
  [kTopDragonflyAlertIdMbxJtagRecovFault] = kTopDragonflyAlertPeripheralMbxJtag,
  [kTopDragonflyAlertIdMbxPcie0FatalFault] = kTopDragonflyAlertPeripheralMbxPcie0,
  [kTopDragonflyAlertIdMbxPcie0RecovFault] = kTopDragonflyAlertPeripheralMbxPcie0,
  [kTopDragonflyAlertIdMbxPcie1FatalFault] = kTopDragonflyAlertPeripheralMbxPcie1,
  [kTopDragonflyAlertIdMbxPcie1RecovFault] = kTopDragonflyAlertPeripheralMbxPcie1,
  [kTopDragonflyAlertIdSocDbgCtrlFatalFault] = kTopDragonflyAlertPeripheralSocDbgCtrl,
  [kTopDragonflyAlertIdSocDbgCtrlRecovCtrlUpdateErr] = kTopDragonflyAlertPeripheralSocDbgCtrl,
  [kTopDragonflyAlertIdRaclCtrlFatalFault] = kTopDragonflyAlertPeripheralRaclCtrl,
  [kTopDragonflyAlertIdRaclCtrlRecovCtrlUpdateErr] = kTopDragonflyAlertPeripheralRaclCtrl,
  [kTopDragonflyAlertIdAcRangeCheckRecovCtrlUpdateErr] = kTopDragonflyAlertPeripheralAcRangeCheck,
  [kTopDragonflyAlertIdAcRangeCheckFatalFault] = kTopDragonflyAlertPeripheralAcRangeCheck,
  [kTopDragonflyAlertIdRvCoreIbexFatalSwErr] = kTopDragonflyAlertPeripheralRvCoreIbex,
  [kTopDragonflyAlertIdRvCoreIbexRecovSwErr] = kTopDragonflyAlertPeripheralRvCoreIbex,
  [kTopDragonflyAlertIdRvCoreIbexFatalHwErr] = kTopDragonflyAlertPeripheralRvCoreIbex,
  [kTopDragonflyAlertIdRvCoreIbexRecovHwErr] = kTopDragonflyAlertPeripheralRvCoreIbex,
};

/**
 * PLIC Interrupt Source to Peripheral Map
 *
 * This array is a mapping from `top_dragonfly_plic_irq_id_t` to
 * `top_dragonfly_plic_peripheral_t`.
 */
const top_dragonfly_plic_peripheral_t
    top_dragonfly_plic_interrupt_for_peripheral[132] = {
  [kTopDragonflyPlicIrqIdNone] = kTopDragonflyPlicPeripheralUnknown,
  [kTopDragonflyPlicIrqIdUart0TxWatermark] = kTopDragonflyPlicPeripheralUart0,
  [kTopDragonflyPlicIrqIdUart0RxWatermark] = kTopDragonflyPlicPeripheralUart0,
  [kTopDragonflyPlicIrqIdUart0TxDone] = kTopDragonflyPlicPeripheralUart0,
  [kTopDragonflyPlicIrqIdUart0RxOverflow] = kTopDragonflyPlicPeripheralUart0,
  [kTopDragonflyPlicIrqIdUart0RxFrameErr] = kTopDragonflyPlicPeripheralUart0,
  [kTopDragonflyPlicIrqIdUart0RxBreakErr] = kTopDragonflyPlicPeripheralUart0,
  [kTopDragonflyPlicIrqIdUart0RxTimeout] = kTopDragonflyPlicPeripheralUart0,
  [kTopDragonflyPlicIrqIdUart0RxParityErr] = kTopDragonflyPlicPeripheralUart0,
  [kTopDragonflyPlicIrqIdUart0TxEmpty] = kTopDragonflyPlicPeripheralUart0,
  [kTopDragonflyPlicIrqIdGpioGpio0] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio1] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio2] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio3] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio4] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio5] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio6] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio7] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio8] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio9] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio10] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio11] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio12] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio13] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio14] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio15] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio16] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio17] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio18] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio19] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio20] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio21] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio22] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio23] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio24] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio25] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio26] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio27] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio28] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio29] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio30] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdGpioGpio31] = kTopDragonflyPlicPeripheralGpio,
  [kTopDragonflyPlicIrqIdSpiDeviceUploadCmdfifoNotEmpty] = kTopDragonflyPlicPeripheralSpiDevice,
  [kTopDragonflyPlicIrqIdSpiDeviceUploadPayloadNotEmpty] = kTopDragonflyPlicPeripheralSpiDevice,
  [kTopDragonflyPlicIrqIdSpiDeviceUploadPayloadOverflow] = kTopDragonflyPlicPeripheralSpiDevice,
  [kTopDragonflyPlicIrqIdSpiDeviceReadbufWatermark] = kTopDragonflyPlicPeripheralSpiDevice,
  [kTopDragonflyPlicIrqIdSpiDeviceReadbufFlip] = kTopDragonflyPlicPeripheralSpiDevice,
  [kTopDragonflyPlicIrqIdSpiDeviceTpmHeaderNotEmpty] = kTopDragonflyPlicPeripheralSpiDevice,
  [kTopDragonflyPlicIrqIdSpiDeviceTpmRdfifoCmdEnd] = kTopDragonflyPlicPeripheralSpiDevice,
  [kTopDragonflyPlicIrqIdSpiDeviceTpmRdfifoDrop] = kTopDragonflyPlicPeripheralSpiDevice,
  [kTopDragonflyPlicIrqIdI2c0FmtThreshold] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0RxThreshold] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0AcqThreshold] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0RxOverflow] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0ControllerHalt] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0SclInterference] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0SdaInterference] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0StretchTimeout] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0SdaUnstable] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0CmdComplete] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0TxStretch] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0TxThreshold] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0AcqStretch] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0UnexpStop] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdI2c0HostTimeout] = kTopDragonflyPlicPeripheralI2c0,
  [kTopDragonflyPlicIrqIdRvTimerTimerExpiredHart0Timer0] = kTopDragonflyPlicPeripheralRvTimer,
  [kTopDragonflyPlicIrqIdOtpCtrlOtpOperationDone] = kTopDragonflyPlicPeripheralOtpCtrl,
  [kTopDragonflyPlicIrqIdOtpCtrlOtpError] = kTopDragonflyPlicPeripheralOtpCtrl,
  [kTopDragonflyPlicIrqIdAlertHandlerClassa] = kTopDragonflyPlicPeripheralAlertHandler,
  [kTopDragonflyPlicIrqIdAlertHandlerClassb] = kTopDragonflyPlicPeripheralAlertHandler,
  [kTopDragonflyPlicIrqIdAlertHandlerClassc] = kTopDragonflyPlicPeripheralAlertHandler,
  [kTopDragonflyPlicIrqIdAlertHandlerClassd] = kTopDragonflyPlicPeripheralAlertHandler,
  [kTopDragonflyPlicIrqIdSpiHost0Error] = kTopDragonflyPlicPeripheralSpiHost0,
  [kTopDragonflyPlicIrqIdSpiHost0SpiEvent] = kTopDragonflyPlicPeripheralSpiHost0,
  [kTopDragonflyPlicIrqIdPwrmgrAonWakeup] = kTopDragonflyPlicPeripheralPwrmgrAon,
  [kTopDragonflyPlicIrqIdAonTimerAonWkupTimerExpired] = kTopDragonflyPlicPeripheralAonTimerAon,
  [kTopDragonflyPlicIrqIdAonTimerAonWdogTimerBark] = kTopDragonflyPlicPeripheralAonTimerAon,
  [kTopDragonflyPlicIrqIdAccDone] = kTopDragonflyPlicPeripheralAcc,
  [kTopDragonflyPlicIrqIdHmacHmacDone] = kTopDragonflyPlicPeripheralHmac,
  [kTopDragonflyPlicIrqIdHmacFifoEmpty] = kTopDragonflyPlicPeripheralHmac,
  [kTopDragonflyPlicIrqIdHmacHmacErr] = kTopDragonflyPlicPeripheralHmac,
  [kTopDragonflyPlicIrqIdKmacKmacDone] = kTopDragonflyPlicPeripheralKmac,
  [kTopDragonflyPlicIrqIdKmacFifoEmpty] = kTopDragonflyPlicPeripheralKmac,
  [kTopDragonflyPlicIrqIdKmacKmacErr] = kTopDragonflyPlicPeripheralKmac,
  [kTopDragonflyPlicIrqIdKeymgrDpeOpDone] = kTopDragonflyPlicPeripheralKeymgrDpe,
  [kTopDragonflyPlicIrqIdCsrngCsCmdReqDone] = kTopDragonflyPlicPeripheralCsrng,
  [kTopDragonflyPlicIrqIdCsrngCsEntropyReq] = kTopDragonflyPlicPeripheralCsrng,
  [kTopDragonflyPlicIrqIdCsrngCsHwInstExc] = kTopDragonflyPlicPeripheralCsrng,
  [kTopDragonflyPlicIrqIdCsrngCsFatalErr] = kTopDragonflyPlicPeripheralCsrng,
  [kTopDragonflyPlicIrqIdEntropySrcEsEntropyValid] = kTopDragonflyPlicPeripheralEntropySrc,
  [kTopDragonflyPlicIrqIdEntropySrcEsHealthTestFailed] = kTopDragonflyPlicPeripheralEntropySrc,
  [kTopDragonflyPlicIrqIdEntropySrcEsObserveFifoReady] = kTopDragonflyPlicPeripheralEntropySrc,
  [kTopDragonflyPlicIrqIdEntropySrcEsFatalErr] = kTopDragonflyPlicPeripheralEntropySrc,
  [kTopDragonflyPlicIrqIdEdn0EdnCmdReqDone] = kTopDragonflyPlicPeripheralEdn0,
  [kTopDragonflyPlicIrqIdEdn0EdnFatalErr] = kTopDragonflyPlicPeripheralEdn0,
  [kTopDragonflyPlicIrqIdEdn1EdnCmdReqDone] = kTopDragonflyPlicPeripheralEdn1,
  [kTopDragonflyPlicIrqIdEdn1EdnFatalErr] = kTopDragonflyPlicPeripheralEdn1,
  [kTopDragonflyPlicIrqIdDmaDmaDone] = kTopDragonflyPlicPeripheralDma,
  [kTopDragonflyPlicIrqIdDmaDmaChunkDone] = kTopDragonflyPlicPeripheralDma,
  [kTopDragonflyPlicIrqIdDmaDmaError] = kTopDragonflyPlicPeripheralDma,
  [kTopDragonflyPlicIrqIdMbx0MbxReady] = kTopDragonflyPlicPeripheralMbx0,
  [kTopDragonflyPlicIrqIdMbx0MbxAbort] = kTopDragonflyPlicPeripheralMbx0,
  [kTopDragonflyPlicIrqIdMbx0MbxError] = kTopDragonflyPlicPeripheralMbx0,
  [kTopDragonflyPlicIrqIdMbx1MbxReady] = kTopDragonflyPlicPeripheralMbx1,
  [kTopDragonflyPlicIrqIdMbx1MbxAbort] = kTopDragonflyPlicPeripheralMbx1,
  [kTopDragonflyPlicIrqIdMbx1MbxError] = kTopDragonflyPlicPeripheralMbx1,
  [kTopDragonflyPlicIrqIdMbx2MbxReady] = kTopDragonflyPlicPeripheralMbx2,
  [kTopDragonflyPlicIrqIdMbx2MbxAbort] = kTopDragonflyPlicPeripheralMbx2,
  [kTopDragonflyPlicIrqIdMbx2MbxError] = kTopDragonflyPlicPeripheralMbx2,
  [kTopDragonflyPlicIrqIdMbx3MbxReady] = kTopDragonflyPlicPeripheralMbx3,
  [kTopDragonflyPlicIrqIdMbx3MbxAbort] = kTopDragonflyPlicPeripheralMbx3,
  [kTopDragonflyPlicIrqIdMbx3MbxError] = kTopDragonflyPlicPeripheralMbx3,
  [kTopDragonflyPlicIrqIdMbx4MbxReady] = kTopDragonflyPlicPeripheralMbx4,
  [kTopDragonflyPlicIrqIdMbx4MbxAbort] = kTopDragonflyPlicPeripheralMbx4,
  [kTopDragonflyPlicIrqIdMbx4MbxError] = kTopDragonflyPlicPeripheralMbx4,
  [kTopDragonflyPlicIrqIdMbx5MbxReady] = kTopDragonflyPlicPeripheralMbx5,
  [kTopDragonflyPlicIrqIdMbx5MbxAbort] = kTopDragonflyPlicPeripheralMbx5,
  [kTopDragonflyPlicIrqIdMbx5MbxError] = kTopDragonflyPlicPeripheralMbx5,
  [kTopDragonflyPlicIrqIdMbx6MbxReady] = kTopDragonflyPlicPeripheralMbx6,
  [kTopDragonflyPlicIrqIdMbx6MbxAbort] = kTopDragonflyPlicPeripheralMbx6,
  [kTopDragonflyPlicIrqIdMbx6MbxError] = kTopDragonflyPlicPeripheralMbx6,
  [kTopDragonflyPlicIrqIdMbxJtagMbxReady] = kTopDragonflyPlicPeripheralMbxJtag,
  [kTopDragonflyPlicIrqIdMbxJtagMbxAbort] = kTopDragonflyPlicPeripheralMbxJtag,
  [kTopDragonflyPlicIrqIdMbxJtagMbxError] = kTopDragonflyPlicPeripheralMbxJtag,
  [kTopDragonflyPlicIrqIdMbxPcie0MbxReady] = kTopDragonflyPlicPeripheralMbxPcie0,
  [kTopDragonflyPlicIrqIdMbxPcie0MbxAbort] = kTopDragonflyPlicPeripheralMbxPcie0,
  [kTopDragonflyPlicIrqIdMbxPcie0MbxError] = kTopDragonflyPlicPeripheralMbxPcie0,
  [kTopDragonflyPlicIrqIdMbxPcie1MbxReady] = kTopDragonflyPlicPeripheralMbxPcie1,
  [kTopDragonflyPlicIrqIdMbxPcie1MbxAbort] = kTopDragonflyPlicPeripheralMbxPcie1,
  [kTopDragonflyPlicIrqIdMbxPcie1MbxError] = kTopDragonflyPlicPeripheralMbxPcie1,
  [kTopDragonflyPlicIrqIdRaclCtrlRaclError] = kTopDragonflyPlicPeripheralRaclCtrl,
  [kTopDragonflyPlicIrqIdAcRangeCheckDenyCntReached] = kTopDragonflyPlicPeripheralAcRangeCheck,
};
