# Copyright zeroRISC Inc.
# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0


from topgen.validate import (top_required, top_optional, top_added,
                             top_seed_required, top_seed_optional,
                             module_required, module_optional)
from reggen.gen_selfdoc import doc_tbl_head, doc_tbl_line

selfdoc_intro = "\n<!-- Start of output generated by topgen.selfdoc -->\n"
selfdoc_outro = "\n<!-- End of output generated by topgen.selfdoc -->\n"


def make_usage_table(outfile, required=None, optional=None, added=None):
    doc_tbl_head(outfile, True)
    if required is not None:
        for k, v in required.items():
            doc_tbl_line(outfile, k, "r", v)
    if optional is not None:
        for k, v in optional.items():
            doc_tbl_line(outfile, k, "o", v)
    if added is not None:
        for k, v in added.items():
            doc_tbl_line(outfile, k, "a", v)


def document(outfile):
    outfile.write(selfdoc_intro)

    outfile.write("All Hjson values should conform to [the value types delineated by"
                  """ `reggen`](../reggen/README.md).
This includes top level Hjsons.

Top Hjsons should also have the following keys (some being optional):
""")
    make_usage_table(outfile, required=top_required, optional=top_optional)

    outfile.write("\nModule Hjsons (referred to by the \"complete config\" Hjson topgen "
                  "creates) has the following keys (some being optional):")
    make_usage_table(outfile, required=module_required, optional=module_optional)

    outfile.write("\nThe \"complete config\" Hjson adds the following keys:\n")
    make_usage_table(outfile, added=top_added)

    outfile.write("""\n\nTops must also come with a seed configuration Hjson.
Seed configs must include the following keys:\n""")
    make_usage_table(outfile, required=top_seed_required,
                     optional=top_seed_optional)

    outfile.write("""\n\nFor an even more detailed look at the subsections of the top Hjson,"""
                  """ refer to [`util/topgen/validate.py`](./validate.py), which contains"""
                  """ dictionaries of various subsection key and value type requirements.
These dictionaries store such requirements in the form of `{<key>: [<abbreviated_value_type>,"""
                  """ <description>]}`.
The variable name of the dictionary will convey whether the value is required, optional, or added.

""")

    outfile.write(selfdoc_outro)
