# Copyright lowRISC contributors (OpenTitan project).
# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
from basegen.validate import BUILTIN_SCHEMAS_REGISTRY
import jsonschema2md
from pathlib import Path

selfdoc_intro = "\n<!-- Start of output generated by topgen.selfdoc -->\n"
selfdoc_outro = "\n<!-- End of output generated by topgen.selfdoc -->\n"

schema_parser = jsonschema2md.Parser(header_level=2)


def document_schema(outfile, schema_uri):
    schema_desc = schema_parser.parse_schema(
        BUILTIN_SCHEMAS_REGISTRY[schema_uri].contents)
    outfile.write("".join(schema_desc))


def document(outfile):
    outfile.write(selfdoc_intro)

    document_schema(outfile, "urn:topgen:topcfg")

    outfile.write("\nThe top configuration partially specifies its list of modules.\n\n")
    document_schema(outfile, "urn:topgen:module")

    outfile.write("\nTops must also come with a seed configuration Hjson.\n\n")
    document_schema(outfile, "urn:topgen:seedcfg")
    outfile.write("\n\n## Other schemas\n\n")

    for schemafile in sorted((Path(__file__).parent / "schemas").iterdir()):
        schema_name = schemafile.stem  # assume schema name matches file name
        if schema_name in ("BUILD", "topcfg", "module", "seedcfg"):
            continue
        document_schema(outfile, f"urn:topgen:{schema_name}")
        outfile.write("\n")

    outfile.write(selfdoc_outro)
