# Copyright lowRISC contributors (OpenTitan project).
# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0


from topgen.validate import (module_required, module_optional)
from reggen.gen_selfdoc import doc_tbl_head, doc_tbl_line
from basegen.validate import BUILTIN_SCHEMAS_REGISTRY
import jsonschema2md
from pathlib import Path

selfdoc_intro = "\n<!-- Start of output generated by topgen.selfdoc -->\n"
selfdoc_outro = "\n<!-- End of output generated by topgen.selfdoc -->\n"

schema_parser = jsonschema2md.Parser(header_level=2)


def document_schema(outfile, schema_uri):
    schema_desc = schema_parser.parse_schema(
        BUILTIN_SCHEMAS_REGISTRY[schema_uri].contents)
    outfile.write("".join(schema_desc))


def make_usage_table(outfile, required=None, optional=None, added=None):
    doc_tbl_head(outfile, True)
    if required is not None:
        for k, v in required.items():
            doc_tbl_line(outfile, k, "r", v)
    if optional is not None:
        for k, v in optional.items():
            doc_tbl_line(outfile, k, "o", v)
    if added is not None:
        for k, v in added.items():
            doc_tbl_line(outfile, k, "a", v)


def document(outfile):
    outfile.write(selfdoc_intro)

    document_schema(outfile, "urn:topgen:topcfg")

    outfile.write("\nModule Hjsons (referred to by the \"complete config\" Hjson topgen "
                  "creates) has the following keys (some being optional):\n")
    make_usage_table(outfile, required=module_required, optional=module_optional)
    outfile.write("\n")

    outfile.write("""\nTops must also come with a seed configuration Hjson.\n""")
    document_schema(outfile, "urn:topgen:seedcfg")
    outfile.write("\n")

    for schemafile in sorted((Path(__file__).parent / "schemas").iterdir()):
        schema_name = schemafile.stem  # assume schema name matches file name
        if schema_name in ("BUILD", "topcfg", "seedcfg"):
            continue
        document_schema(outfile, f"urn:topgen:{schema_name}")
        outfile.write("\n")

    outfile.write(selfdoc_outro)
