# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

exports_files(glob(["**/*"]))

filegroup(
    name = "schemas",
    srcs = [
        "alert.hjson",
        "alias.hjson",
        "bus_interface.hjson",
        "clocking_item.hjson",
        "countermeasure.hjson",
        "enum_entry.hjson",
        "feature.hjson",
        "field.hjson",
        "inter_signal.hjson",
        "interrupt.hjson",
        "ip_block.hjson",
        "multiregister.hjson",
        "parameter.hjson",
        "register.hjson",
        "revision.hjson",
        "signal.hjson",
        "window.hjson",
    ],
)
