# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

exports_files(glob(["**/*"]))

filegroup(
    name = "schemas",
    srcs = [
        "pad.hjson",
        "pinmux.hjson",
        "pinmux_io.hjson",
        "pinmux_io_count.hjson",
        "pinmux_signal.hjson",
        "pinout.hjson",
        "seedcfg.hjson",
        "special_signal.hjson",
        "straps.hjson",
        "target.hjson",
        "target_pinmux.hjson",
        "target_pinout.hjson",
        "topcfg.hjson",
    ],
)
