// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_${xbar.name}_sim_cfg.hjson file generated by `tlgen.py` tool<%
def adapt_filepath(filepath):
    return str(filepath).replace("xbar_" + xbar.name, "{dut}")%>
{
  name: xbar_${xbar.name}

  // Top level dut name (sv module).
  dut: xbar_${xbar.name}

  // The name of the chip this XBAR configuration is made for.
  top_chip: ${library_name}

  // The name of the top that contains this XBAR
  variant: ${library_name.replace("top_", "")}

  // Testplan hjson file.
  testplan: "{proj_root}/hw/ip/tlul/data/tlul_testplan.hjson"

  // Add xbar_main specific exclusion files.
  vcs_cov_excl_files: ["{proj_root}/${adapt_filepath(dv_filepath.parent)}/xbar_cov_excl.el"]

  // replace common cover.cfg with a generated one, which includes xbar toggle exclusions
  overrides: [
    {
      name: default_vcs_cov_cfg_file
      value: "-cm_hier {proj_root}/${adapt_filepath(dv_filepath.parent)}/xbar_cover.cfg"
    }
    {
      name: scratch_path
      value: "{scratch_base_path}/{name}_{topname}-{flow}-{tool}"
    }
  ]
  // Import additional common sim cfg files.
  import_cfgs: [// xbar common sim cfg file
                "{proj_root}/hw/ip/tlul/generic_dv/xbar_sim_cfg.hjson"]
}
