# Copyright lowRISC contributors (OpenTitan project).
# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: "00 02 * * 2-5" # 2:00 am Tuesday thru Friday

permissions:
  contents: read
  # Needed for workload identity federation
  id-token: write

jobs:
  # Run On-demand Tests
  on-demand:
    name: Run On-demand Tests
    permissions:
      contents: read
      id-token: write
      # Required by verible_lint job, even though it doesn't run
      pull-requests: write
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  # Hyper310 nightly FPGA jobs
  execute_nightly_tests_egret_cw310:
    name: Egret CW310 Nightly Tests
    needs: on-demand
    if: success() || failure()
    uses: ./.github/workflows/egret-cw310-nightly.yml
    secrets: inherit
    with:
      bitstream: chip_egret_cw310_hyperdebug

  # CW340 nightly FPGA jobs
  execute_nightly_tests_egret_cw340:
    name: Egret CW340 Nightly Tests
    needs: on-demand
    if: success() || failure()
    uses: ./.github/workflows/egret-cw340-nightly.yml
    secrets: inherit
    with:
      bitstream: chip_egret_cw340

  # DVSim nightly
  dvsim-all:
    name: All nightly DVSim coverage simulation
    uses: ./.github/workflows/dv-all.yml
    secrets: inherit
    with:
      item: "nightly"
      run-type: "nightly"
      coverage: true
      timeout-minutes: 2880 # 48 hours
      dashboard-private: "git@github.com:pavona/internal-dashboard.git"
      dashboard-public: "git@github.com:pavona/public-dashboard.git"
      concurrent-jobs: 25
