# Copyright zeroRISC Inc.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Weekly
on:
  schedule:
    # Start weekly run at 2:00a GMT every Saturday morning.
    # (7:00p PT, 10:00p ET, 3:00a CET)
    - cron: "00 02 * * SAT"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dvsim-all:
    name: All weekly DVSim coverage simulation
    uses: ./.github/workflows/dv-all.yml
    secrets: inherit
    with:
      runner: "pavona-dv-large"
      run-type: "weekly"
      item: "weekly"
      coverage: true
      timeout-minutes: 9000 # 150 hours
      dashboard-private: "git@github.com:pavona/internal-dashboard.git"
      dashboard-public: "git@github.com:pavona/public-dashboard.git"
      reseed-source: "hw/dv/grading/grading_report.hjson"
      concurrent-jobs: 28

  gitless:
    name: Run gitless check (repo packaging check)
    runs-on:
      group: pavona-large
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Prepare environment
        uses: ./.github/actions/prepare-env
      - name: Work from git repo archive
        run: |
          git archive --format=tar.gz -o "../gitless.tar.gz" HEAD
          cd ..
          mkdir gitless
          tar -xzf gitless.tar.gz -C gitless --strip-components=1
          cd gitless
          export REPO_TOP=$(realpath .)
      - name: Run gitless check
        continue-on-error: true
        run: ./ci/scripts/check-gitless.sh -e
      - name: Output gitless log
        run: |
          log_output=$(cat gitless.log)  # will be empty if no errors
          if [ -n "$log_output" ]; then
            echo $log_output
            exit 1
          fi
